### ISSUE TITLE
reading mat file for comparison

### ISSUE THREAD

**Issue by alexlib** [alexlib/openpiv_pivlab_von_Karman_data#1]
Hi @Shrediquette - could you please tell me what variable from the MAT file I need to read to plot your vorticity outside of PIVlab? I try to do it from Python using h5py package.

**Comment by Shrediquette** [comment]
Hi Alex, the variable is called 'derived'. Each column contains a 2D matrix of vorticity.
The coordinates (X and y) are in the variable 'resultslist'. First row contains X coordinates in 2D format, second row contains y coordinates in 2D format.
This mat file actually is only for Pivlab's internal use ( it is a 'session' file), so the data is organized in a somewhat strange way.

**Comment by alexlib** [comment]
so we're close to the moment of comparison. I just need to double check the parameters for the openpiv and whether it uses smoothing or not

https://github.com/alexlib/openpiv_pivlab_von_Karman_data/blob/main/OpenPIV/plot_pivlab_results.ipynb
https://github.com/alexlib/openpiv_pivlab_von_Karman_data/blob/main/OpenPIV/vonKarman_openpiv_pivpy_vorticity.ipynb

**Comment by Shrediquette** [comment]
Hi, if you have finished th comparison, please let me know. Today I went through a couple of your commits (jupyter notebooks), but I didn't see a vorticity result yet.
