### ISSUE TITLE
Result comparison

### ISSUE THREAD

**Issue by Shrediquette** [alexlib/openpiv_pivlab_von_Karman_data#2]
Hi Alex, so, if I open this website on a computer, I can actually see the results :-D
_I guess this is the relevant result for Openpiv:_
https://github.com/alexlib/openpiv_pivlab_von_Karman_data/blob/main/OpenPIV/vonKarman_openpiv_pivpy_vorticity.ipynb

_and this for PIVlab:_
https://github.com/alexlib/openpiv_pivlab_von_Karman_data/blob/main/OpenPIV/plot_pivlab_results.ipynb

I put the images side by side here (and also attached):
https://drive.google.com/file/d/1-U5Bw0ae7OMnMXKiqO8curH4a1ydyUAD/view?usp=sharing

I think OpenPIV is better in the shadow area. But it doesn't show any of the vortices rolling up behind the cylinder...? OpenPIV seems to be really noisy in the wake. Is that an issue of the vorticity calculation, or of the velocity calculation?
![PIVlab_vs_Openpiv](https://user-images.githubusercontent.com/42935970/102887413-3495ad00-4457-11eb-97d3-076b06575dba.jpg)

**Comment by alexlib** [comment]
> Hi Alex, so, if I open this website on a computer, I can actually see the results :-D
> 
> _I guess this is the relevant result for Openpiv:_
> 
> https://github.com/alexlib/openpiv_pivlab_von_Karman_data/blob/main/OpenPIV/vonKarman_openpiv_pivpy_vorticity.ipynb
> 
> 
> 
> _and this for PIVlab:_
> 
> https://github.com/alexlib/openpiv_pivlab_von_Karman_data/blob/main/OpenPIV/plot_pivlab_results.ipynb
> 
> 
> 
> I put the images side by side here (and also attached):
> 
> https://drive.google.com/file/d/1-U5Bw0ae7OMnMXKiqO8curH4a1ydyUAD/view?usp=sharing
> 
> 
> 
> I think OpenPIV is better in the shadow area. But it doesn't show any of the vortices rolling up behind the cylinder...? OpenPIV seems to be really noisy in the wake. Is that an issue of the vorticity calculation, or of the velocity calculation?
> 
> ![PIVlab_vs_Openpiv](https://user-images.githubusercontent.com/42935970/102887413-3495ad00-4457-11eb-97d3-076b06575dba.jpg)
> 
> 

Hi William, 

I see you found it :)

You could not believe where this comparison led me to ;) We had some dynamic masking that was applied to every image pair, but this was not actually a "real" mask, but more a set of zero velocity values. Now, with the windows deformation multi pass the zero values are interpolated and lead to some bias (and probably some part of the later noise appearance at small window sizes). But as I tried to implement the "proper" image mask that can be preserved between multi-pass iterations, and all that mess, I'm for two weeks cannot do almost anything but to debug OpenPIV. So please bare with me until I'll finish and then, hopefully we'll get a less noisy result that I'll be proud to share. Or I'll fail and we'll get back to the result you see right now. 
Open for your ideas and suggestions. Thanks for investing your time in it. 
How do you manage to keep PIVLab by your own?

**Comment by Shrediquette** [comment]
Hi Alex, ok, just let me know as soon as you have better results!

**Comment by alexlib** [comment]
I already see the vortices :) just need to figure out why they're opposite vorticity sign. You have the origin at top left corner, but your data is in the right-hand coordinate system, right? i.e. x to the right, y is upwards and dv/dx - du/dy is positive when counterclockwise.

**Comment by Shrediquette** [comment]
Hi Alex I think my vorticity has the wrong sign. AFAIK I completely use the image coordinate system.

**Comment by alexlib** [comment]
I pushed the updated version @Shrediquette, please take a look https://github.com/alexlib/openpiv_pivlab_von_Karman_data/blob/main/OpenPIV/vonKarman_openpiv_plot_results.ipynb 

Do you want me to create also PIVLab identical view notebook?

**Comment by Shrediquette** [comment]
Hi Alex, it would be awesome if you would create a side-by-side figure as above, and maybe invert one of the colour bars (or invert vorticity). 
Have a peaceful end-of-the-year-period!!

**Comment by alexlib** [comment]
pushed it 
![side_to_side](https://user-images.githubusercontent.com/747110/103179116-5648c700-4891-11eb-8319-37c5815664a5.png)

**Comment by alexlib** [comment]
Hi @Shrediquette - Happy New Year. Shall we release this work by making it public?

**Comment by Shrediquette** [comment]
Hi Alex, yes please! I don't see any difference however... Do you?

**Comment by alexlib** [comment]
There are small differences, but really minor. I see it as a good sign :)
